services:
  - type: web
    name: rag-doc-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: VECTORSTORE_PATH
        value: /opt/render/project/src/vectorstore
    disk:
      name: vectorstore
      mountPath: /opt/render/project/src/vectorstore
      sizeGB: 1
